// モックデータ
export const mockProjects = [
  {
    id: '1',
    orderNo: '37-098',
    type: '機械',
    clientName: '○○建設',
    siteName: '○○浄化センター',
    projectName: '中央監視設備更新工事',
    manager: '田中',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-09-01',
    endDate: '2026-02-28',
    isCorins: true,
    amount: 45000000,
    progress: 35,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '2',
    orderNo: '37-099',
    type: '電気',
    clientName: '△△工業',
    siteName: '△△ポンプ場',
    projectName: '受変電設備改修工事',
    manager: '佐藤',
    engineer: '鈴木一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-15',
    endDate: '2025-11-30',
    isCorins: false,
    amount: 8500000,
    progress: 0,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '3',
    orderNo: '37-100',
    type: '機械',
    clientName: '□□市役所',
    siteName: '□□処理場',
    projectName: 'ポンプ設備更新工事',
    manager: '高橋',
    engineer: '伊藤次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2025-10-01',
    endDate: '2026-04-30',
    isCorins: true,
    amount: 125000000,
    progress: 45,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '4',
    orderNo: '37-101',
    type: '電気',
    clientName: '××病院',
    siteName: '新館',
    projectName: 'LED照明更新',
    manager: '鈴木',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-20',
    endDate: '2025-10-31',
    isCorins: false,
    amount: 8500000,
    progress: 60,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '5',
    orderNo: '37-102',
    type: '機械',
    clientName: '▽▽ビル',
    siteName: '地下機械室',
    projectName: 'ボイラー更新工事',
    manager: '高橋',
    engineer: '杉田次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2025-11-01',
    endDate: '2026-01-31',
    isCorins: true,
    amount: 38000000,
    progress: 25,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '6',
    orderNo: '38-002',
    type: '電気',
    clientName: '○○学校',
    siteName: '体育館',
    projectName: '音響設備改修',
    manager: '田中',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-12-01',
    endDate: '2026-01-15',
    isCorins: false,
    amount: 12000000,
    progress: 10,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '7',
    orderNo: '37-103',
    type: '機械',
    clientName: '△△ホテル',
    siteName: '本館',
    projectName: 'エレベーター改修',
    manager: '山田',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-25',
    endDate: '2025-10-31',
    isCorins: false,
    amount: 25000000,
    progress: 75,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '8',
    orderNo: '38-003',
    type: '電気',
    clientName: '◎◎工場',
    siteName: '第1プラント',
    projectName: '動力盤更新',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: true,
    startDate: '2026-01-01',
    endDate: '2026-05-31',
    isCorins: true,
    amount: 48000000,
    progress: 5,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '9',
    orderNo: '37-104',
    type: '機械',
    clientName: '▲▲マンション',
    siteName: '共用部',
    projectName: '給水ポンプ交換',
    manager: '鈴木',
    engineer: '杉田次郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-10-10',
    endDate: '2025-11-15',
    isCorins: false,
    amount: 5500000,
    progress: 20,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '10',
    orderNo: '37-105',
    type: '電気',
    clientName: '■■商業施設',
    siteName: 'B館',
    projectName: '防災設備更新',
    manager: '高橋',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-09-05',
    endDate: '2025-10-20',
    isCorins: false,
    amount: 15000000,
    progress: 90,
    status: '施工中',
    currentPhase: '竣工フェーズ',
  },
  {
    id: '11',
    orderNo: '38-004',
    type: '機械',
    clientName: '☆☆病院',
    siteName: '本館',
    projectName: '空調設備改修',
    manager: '田中',
    engineer: '中村三郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-02-01',
    endDate: '2026-05-31',
    isCorins: false,
    amount: 32000000,
    progress: 30,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '12',
    orderNo: '37-106',
    type: '電気',
    clientName: '◇◇工業',
    siteName: '第2工場',
    projectName: '受変電設備改修',
    manager: '山田',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-03-01',
    endDate: '2026-05-31',
    isCorins: false,
    amount: 15000000,
    progress: 50,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '13',
    orderNo: '38-005',
    type: '機械',
    clientName: '○○市',
    siteName: '市民会館',
    projectName: '給排水設備更新',
    manager: '佐藤',
    engineer: '杉田次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2026-01-15',
    endDate: '2026-07-31',
    isCorins: true,
    amount: 65000000,
    progress: 0,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '14',
    orderNo: '37-107',
    type: '電気',
    clientName: '△△大学',
    siteName: '研究棟',
    projectName: '実験設備電源工事',
    manager: '鈴木',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-04-01',
    endDate: '2026-07-15',
    isCorins: false,
    amount: 22000000,
    progress: 15,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '15',
    orderNo: '38-006',
    type: '機械',
    clientName: '××ビル',
    siteName: '屋上',
    projectName: '冷却塔更新',
    manager: '高橋',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-15',
    endDate: '2025-12-24',
    isCorins: false,
    amount: 9800000,
    progress: 55,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
];

export const mockTasks = {
  '1': {
    契約フェーズ: [
      { id: 't1', name: '契約書締結', completed: false, deadline: '2025-09-05', assignee: '田中' },
      { id: 't2', name: 'CORINS登録要否確認', completed: false, deadline: '2025-09-06', assignee: '田中' },
      { id: 't3', name: '現場代理人選任通知', completed: false, deadline: '2025-09-07', assignee: '田中' },
      { id: 't4', name: '主任技術者選任通知', completed: false, deadline: '2025-09-07', assignee: '田中' },
      { id: 't5', name: 'CORINS登録（契約）', completed: false, deadline: '2025-09-08', assignee: '田中' },
    ],
    着工準備フェーズ: [
      { id: 't6', name: '工程表提出', completed: false, deadline: '2025-09-10', assignee: '田中' },
      { id: 't7', name: '施工計画書作成', completed: false, deadline: '2025-09-15', assignee: '山田太郎' },
      { id: 't8', name: '施工体制台帳作成', completed: false, deadline: '2025-09-20', assignee: '田中' },
      { id: 't9', name: '設計図書照査', completed: false, deadline: '2025-09-18', assignee: '山田太郎' },
    ],
    施工フェーズ: [
      { id: 't10', name: '施工状況報告書', completed: false, deadline: '2025-09-30', assignee: '田中' },
      { id: 't11', name: '工程会議', completed: false, deadline: '2025-09-25', assignee: '山田太郎' },
      { id: 't12', name: '工事写真撮影', completed: false, deadline: '2025-09-28', assignee: '山田太郎' },
    ],
  },
  '2': {
    契約フェーズ: [
      { id: 't21', name: '契約書締結', completed: false, deadline: '2025-09-10', assignee: '佐藤' },
      { id: 't22', name: '現場代理人選任通知', completed: false, deadline: '2025-09-12', assignee: '佐藤' },
      { id: 't23', name: '主任技術者選任通知', completed: false, deadline: '2025-09-12', assignee: '鈴木一郎' },
    ],
  },
  '3': {
    施工フェーズ: [
      { id: 't31', name: '施工状況報告書', completed: false, deadline: '2025-09-15', assignee: '高橋' },
      { id: 't32', name: '工程会議', completed: false, deadline: '2025-09-20', assignee: '伊藤次郎' },
      { id: 't33', name: '工事写真撮影', completed: false, deadline: '2025-09-22', assignee: '伊藤次郎' },
    ],
  },
  '4': {
    施工フェーズ: [
      { id: 't41', name: '工事写真撮影', completed: false, deadline: '2025-09-08', assignee: '髙峯一郎' },
      { id: 't42', name: '施工状況報告書', completed: false, deadline: '2025-09-10', assignee: '鈴木' },
    ],
  },
  '5': {
    着工準備フェーズ: [
      { id: 't51', name: '工程表提出', completed: false, deadline: '2025-09-14', assignee: '高橋' },
      { id: 't52', name: '施工計画書作成', completed: false, deadline: '2025-09-16', assignee: '杉田次郎' },
    ],
  },
  '6': {
    契約フェーズ: [
      { id: 't61', name: '契約書締結', completed: false, deadline: '2025-09-18', assignee: '田中' },
      { id: 't62', name: 'CORINS登録要否確認', completed: false, deadline: '2025-09-19', assignee: '髙峯一郎' },
    ],
  },
  '7': {
    施工フェーズ: [
      { id: 't71', name: '工程会議', completed: false, deadline: '2025-09-13', assignee: '中村三郎' },
      { id: 't72', name: '工事写真撮影', completed: false, deadline: '2025-09-17', assignee: '中村三郎' },
    ],
  },
  '8': {
    契約フェーズ: [
      { id: 't81', name: '契約書締結', completed: false, deadline: '2025-09-20', assignee: '佐藤' },
      { id: 't82', name: 'CORINS登録（契約）', completed: false, deadline: '2025-09-22', assignee: '髙峯一郎' },
    ],
  },
  '9': {
    着工準備フェーズ: [
      { id: 't91', name: '工程表提出', completed: false, deadline: '2025-09-24', assignee: '鈴木' },
      { id: 't92', name: '施工計画書作成', completed: false, deadline: '2025-09-26', assignee: '杉田次郎' },
    ],
  },
  '10': {
    竣工フェーズ: [
      { id: 't101', name: '完成図書作成', completed: false, deadline: '2025-09-15', assignee: '高橋' },
      { id: 't102', name: '工事写真整理', completed: false, deadline: '2025-09-17', assignee: '山田太郎' },
      { id: 't103', name: '竣工検査申請', completed: false, deadline: '2025-09-19', assignee: '高橋' },
      { id: 't104', name: '竣工検査立会', completed: false, deadline: '2025-09-20', assignee: '山田太郎' },
    ],
  },
  '11': {
    施工フェーズ: [
      { id: 't111', name: '機器据付開始', completed: false, deadline: '2025-09-13', assignee: '中村三郎' },
      { id: 't112', name: '配管接続作業', completed: false, deadline: '2025-09-18', assignee: '中村三郎' },
      { id: 't113', name: '中間検査', completed: false, deadline: '2025-09-25', assignee: '田中' },
      { id: 't114', name: '試運転調整', completed: false, deadline: '2025-09-30', assignee: '中村三郎' },
    ],
  },
  '12': {
    施工フェーズ: [
      { id: 't121', name: '既設機器撤去', completed: false, deadline: '2025-09-07', assignee: '髙峯一郎' },
      { id: 't122', name: '新設機器搬入', completed: false, deadline: '2025-09-10', assignee: '髙峯一郎' },
      { id: 't123', name: '配線工事', completed: false, deadline: '2025-09-15', assignee: '髙峯一郎' },
      { id: 't124', name: '動作確認', completed: false, deadline: '2025-09-20', assignee: '山田' },
    ],
  },
  '13': {
    契約フェーズ: [
      { id: 't131', name: '契約書締結', completed: false, deadline: '2025-09-25', assignee: '佐藤' },
      { id: 't132', name: 'CORINS登録要否確認', completed: false, deadline: '2025-09-26', assignee: '佐藤' },
      { id: 't133', name: '現場代理人選任通知', completed: false, deadline: '2025-09-27', assignee: '杉田次郎' },
      { id: 't134', name: '主任技術者選任通知', completed: false, deadline: '2025-09-27', assignee: '杉田次郎' },
      { id: 't135', name: 'CORINS登録（契約）', completed: false, deadline: '2025-09-28', assignee: '佐藤' },
    ],
  },
  '14': {
    着工準備フェーズ: [
      { id: 't141', name: '現場調査', completed: false, deadline: '2025-09-16', assignee: '山田太郎' },
      { id: 't142', name: '設計図書照査', completed: false, deadline: '2025-09-18', assignee: '山田太郎' },
      { id: 't143', name: '工程表作成', completed: false, deadline: '2025-09-20', assignee: '鈴木' },
      { id: 't144', name: '施工計画書作成', completed: false, deadline: '2025-09-22', assignee: '鈴木' },
    ],
  },
  '15': {
    施工フェーズ: [
      { id: 't151', name: '既設冷却塔解体', completed: false, deadline: '2025-09-09', assignee: '中村三郎' },
      { id: 't152', name: '基礎補強工事', completed: false, deadline: '2025-09-12', assignee: '中村三郎' },
      { id: 't153', name: '新設冷却塔据付', completed: false, deadline: '2025-09-16', assignee: '中村三郎' },
      { id: 't154', name: '配管接続・試運転', completed: false, deadline: '2025-09-20', assignee: '高橋' },
      { id: 't155', name: '完了検査', completed: false, deadline: '2025-09-24', assignee: '高橋' },
    ],
  },
};

export const mockStaff = [
  { id: 's1', name: '山田太郎', qualification: '1級電気工事施工管理技士', specialty: '電気', availability: 100 },
  { id: 's2', name: '鈴木一郎', qualification: '1級管工事施工管理技士', specialty: '機械', availability: 80 },
  { id: 's3', name: '伊藤次郎', qualification: '1級土木施工管理技士', specialty: '機械', availability: 60 },
  { id: 's4', name: '田中三郎', qualification: '2級電気工事施工管理技士', specialty: '電気', availability: 100 },
  { id: 's5', name: '高橋四郎', qualification: '1級管工事施工管理技士', specialty: '機械', availability: 40 },
];

export const urgentTasks = [
  { id: 'u1', projectName: '中央監視設備更新工事', taskName: '施工体制台帳作成', deadline: '2025-09-20', daysLeft: 2 },
  { id: 'u2', projectName: '中央監視設備更新工事', taskName: '設計図書照査', deadline: '2025-09-18', daysLeft: 0 },
  { id: 'u3', projectName: '受変電設備改修工事', taskName: '工程表提出', deadline: '2025-09-25', daysLeft: 3 },
];