// モックデータ
export const mockProjects = [
  {
    id: '1',
    orderNo: '37-098',
    workType: '工事',
    type: '機械',
    clientName: '○○建設',
    siteName: '○○浄化センター',
    projectName: '中央監視設備更新工事',
    manager: '田中',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-09-01',
    endDate: '2026-02-28',
    isCorins: true,
    amount: 45000000,
    progress: 35,
    status: '施工中',
    currentPhase: '施工フェーズ',
    partnerIds: ['1', '2'], // 株式会社山本工業 + 有限会社田中電設
  },
  {
    id: '2',
    orderNo: '37-099',
    workType: '工事',
    type: '電気',
    clientName: '△△工業',
    siteName: '△△ポンプ場',
    projectName: '受変電設備改修工事',
    manager: '佐藤',
    engineer: '鈴木一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-15',
    endDate: '2025-11-30',
    isCorins: false,
    amount: 8500000,
    progress: 0,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '3',
    orderNo: '37-100',
    workType: '工事',
    type: '機械',
    clientName: '□□市役所',
    siteName: '□□処理場',
    projectName: 'ポンプ設備更新工事',
    manager: '高橋',
    engineer: '伊藤次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2025-10-01',
    endDate: '2026-04-30',
    isCorins: true,
    amount: 125000000,
    progress: 45,
    status: '施工中',
    currentPhase: '施工フェーズ',
    partnerIds: ['1', '2', '3'], // 株式会社山本工業 + 有限会社田中電設 + 鈴木建設株式会社
  },
  {
    id: '4',
    orderNo: '37-101',
    workType: '工事',
    type: '電気',
    clientName: '××病院',
    siteName: '新館',
    projectName: 'LED照明更新',
    manager: '鈴木',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-20',
    endDate: '2025-10-31',
    isCorins: false,
    amount: 8500000,
    progress: 60,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '5',
    orderNo: '37-102',
    workType: '工事',
    type: '機械',
    clientName: '▽▽ビル',
    siteName: '地下機械室',
    projectName: 'ボイラー更新工事',
    manager: '高橋',
    engineer: '杉田次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2025-11-01',
    endDate: '2026-01-31',
    isCorins: true,
    amount: 38000000,
    progress: 25,
    status: '施工中',
    partnerIds: ['2', '3'], // 有限会社田中電設 + 鈴木建設株式会社
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '6',
    orderNo: '38-002',
    workType: '工事',
    type: '電気',
    clientName: '○○学校',
    siteName: '体育館',
    projectName: '音響設備改修',
    manager: '田中',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-12-01',
    endDate: '2026-01-15',
    isCorins: false,
    amount: 12000000,
    progress: 10,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '7',
    orderNo: '37-103',
    workType: '工事',
    type: '機械',
    clientName: '△△ホテル',
    siteName: '本館',
    projectName: 'エレベーター改修',
    manager: '山田',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-25',
    endDate: '2025-10-31',
    isCorins: false,
    amount: 25000000,
    progress: 75,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '8',
    orderNo: '38-003',
    workType: '工事',
    type: '電気',
    clientName: '◎◎工場',
    siteName: '第1プラント',
    projectName: '動力盤更新',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: true,
    startDate: '2026-01-01',
    endDate: '2026-05-31',
    isCorins: true,
    amount: 48000000,
    progress: 5,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '9',
    orderNo: '37-104',
    workType: '工事',
    type: '機械',
    clientName: '▲▲マンション',
    siteName: '共用部',
    projectName: '給水ポンプ交換',
    manager: '鈴木',
    engineer: '杉田次郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-10-10',
    endDate: '2025-11-15',
    isCorins: false,
    amount: 5500000,
    progress: 20,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '10',
    orderNo: '37-105',
    workType: '工事',
    type: '電気',
    clientName: '■■商業施設',
    siteName: 'B館',
    projectName: '防災設備更新',
    manager: '高橋',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-09-05',
    endDate: '2025-10-20',
    isCorins: false,
    amount: 15000000,
    progress: 90,
    status: '施工中',
    currentPhase: '竣工フェーズ',
    partnerIds: ['1', '3'], // 株式会社山本工業 + 鈴木建設株式会社
  },
  {
    id: '11',
    orderNo: '38-004',
    workType: '工事',
    type: '機械',
    clientName: '☆☆病院',
    siteName: '本館',
    projectName: '空調設備改修',
    manager: '田中',
    engineer: '中村三郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-02-01',
    endDate: '2026-05-31',
    isCorins: false,
    amount: 32000000,
    progress: 30,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '12',
    orderNo: '37-106',
    workType: '工事',
    type: '電気',
    clientName: '◇◇工業',
    siteName: '第2工場',
    projectName: '受変電設備改修',
    manager: '山田',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-03-01',
    endDate: '2026-05-31',
    isCorins: false,
    amount: 15000000,
    progress: 50,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '13',
    orderNo: '38-005',
    workType: '工事',
    type: '機械',
    clientName: '○○市',
    siteName: '市民会館',
    projectName: '給排水設備更新',
    manager: '佐藤',
    engineer: '杉田次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2026-01-15',
    endDate: '2026-07-31',
    isCorins: true,
    amount: 65000000,
    progress: 0,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '14',
    orderNo: '37-107',
    workType: '工事',
    type: '電気',
    clientName: '△△大学',
    siteName: '研究棟',
    projectName: '実験設備電源工事',
    manager: '鈴木',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-04-01',
    endDate: '2026-07-15',
    isCorins: false,
    amount: 22000000,
    progress: 15,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '15',
    orderNo: '38-006',
    workType: '工事',
    type: '機械',
    clientName: '××ビル',
    siteName: '屋上',
    projectName: '冷却塔更新',
    manager: '高橋',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-15',
    endDate: '2025-12-24',
    isCorins: false,
    amount: 9800000,
    progress: 55,
    status: '施工中',
    currentPhase: '施工フェーズ',
    partnerIds: ['2', '1'], // 有限会社田中電設 + 株式会社山本工業
  },
  {
    id: '16',
    orderNo: '38-007',
    workType: '工事',
    type: '鋼造',
    clientName: '○○建設',
    siteName: '新築現場',
    projectName: '鉄骨構造物組立工事',
    manager: '田中',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    isCorins: true,
    amount: 75000000,
    progress: 20,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '17',
    orderNo: '38-008',
    workType: '工事',
    type: '通信',
    clientName: '△△通信',
    siteName: '基地局',
    projectName: '通信設備設置工事',
    manager: '佐藤',
    engineer: '鈴木一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-20',
    endDate: '2025-11-15',
    isCorins: false,
    amount: 18000000,
    progress: 45,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '18',
    orderNo: '38-009',
    workType: '工事',
    type: '納品',
    clientName: '□□商事',
    siteName: '倉庫',
    projectName: '機械設備納品',
    manager: '高橋',
    engineer: '伊藤次郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-10-05',
    endDate: '2025-10-20',
    isCorins: false,
    amount: 12000000,
    progress: 80,
    status: '施工中',
    currentPhase: '竣工フェーズ',
  },
  {
    id: '19',
    orderNo: '38-010',
    workType: '工事',
    type: 'その他',
    clientName: '××企業',
    siteName: '本社',
    projectName: '特殊設備メンテナンス',
    manager: '鈴木',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-10',
    endDate: '2025-10-31',
    isCorins: false,
    amount: 8500000,
    progress: 60,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  // 保守点検（スポット案件 - 月内1〜2日、3ヶ月に1回程度）
  {
    id: '20',
    orderNo: '38-M01',
    workType: '保守点検',
    type: '機械',
    clientName: '○○浄化センター',
    siteName: '中央監視室',
    projectName: '中央監視設備定期点検',
    manager: '田中',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-10-20',
    endDate: '2025-10-21',
    isCorins: false,
    amount: 250000,
    progress: 100,
    status: '完了',
    currentPhase: '点検',
    partnerIds: ['3', '2', '1'], // 鈴木建設株式会社 + 有限会社田中電設 + 株式会社山本工業
  },
  {
    id: '21',
    orderNo: '38-M02',
    workType: '保守点検',
    type: '電気',
    clientName: '△△ポンプ場',
    siteName: '受変電室',
    projectName: '受変電設備年次点検',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-01-15',
    endDate: '2026-01-16',
    isCorins: false,
    amount: 180000,
    progress: 0,
    status: '未着手',
    currentPhase: '点検',
  },
  {
    id: '22',
    orderNo: '38-M03',
    workType: '保守点検',
    type: '機械',
    clientName: '□□処理場',
    siteName: 'ポンプ棟',
    projectName: 'ポンプ設備定期保守',
    manager: '高橋',
    engineer: '伊藤次郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-04-22',
    endDate: '2026-04-22',
    isCorins: false,
    amount: 320000,
    progress: 0,
    status: '未着手',
    currentPhase: '保守',
  },
  {
    id: '23',
    orderNo: '38-M04',
    workType: '保守点検',
    type: '電気',
    clientName: '◎◎工場',
    siteName: '第1プラント',
    projectName: '動力盤定期点検',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-07-10',
    endDate: '2026-07-10',
    isCorins: false,
    amount: 150000,
    progress: 0,
    status: '未着手',
    currentPhase: '点検',
  },
  {
    id: '28',
    orderNo: '38-M05',
    workType: '保守点検',
    type: '機械',
    clientName: '▲▲施設',
    siteName: '空調機械室',
    projectName: '空調設備定期点検',
    manager: '田中',
    engineer: '中村三郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-10-25',
    endDate: '2026-10-25',
    isCorins: false,
    amount: 200000,
    progress: 0,
    status: '未着手',
    currentPhase: '点検',
  },
  {
    id: '29',
    orderNo: '38-M06',
    workType: '保守点検',
    type: '電気',
    clientName: '■■センター',
    siteName: '電気室',
    projectName: '非常用発電機点検',
    manager: '高橋',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2027-01-20',
    endDate: '2027-01-21',
    isCorins: false,
    amount: 280000,
    progress: 0,
    status: '未着手',
    currentPhase: '点検',
  },
  // 機器制作（スポット案件 - 月内1〜2日、3ヶ月に1回程度）
  {
    id: '24',
    orderNo: '38-K01',
    workType: '機器制作',
    type: '機械',
    clientName: '▽▽ビル',
    siteName: '機械工場',
    projectName: 'ボイラー部品製作',
    manager: '高橋',
    engineer: '杉田次郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-11-18',
    endDate: '2025-11-19',
    isCorins: false,
    amount: 450000,
    progress: 50,
    status: '施工中',
    currentPhase: '製作',
  },
  {
    id: '25',
    orderNo: '38-K02',
    workType: '機器制作',
    type: '電気',
    clientName: '○○学校',
    siteName: '工場',
    projectName: '音響設備制御盤製作',
    manager: '田中',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-02-05',
    endDate: '2026-02-06',
    isCorins: false,
    amount: 680000,
    progress: 0,
    status: '未着手',
    currentPhase: '製作',
  },
  {
    id: '26',
    orderNo: '38-K03',
    workType: '機器制作',
    type: '機械',
    clientName: '☆☆病院',
    siteName: '協力工場',
    projectName: '空調設備ダクト製作',
    manager: '田中',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-05-12',
    endDate: '2026-05-12',
    isCorins: false,
    amount: 580000,
    progress: 0,
    status: '未着手',
    currentPhase: '製作',
  },
  {
    id: '27',
    orderNo: '38-K04',
    workType: '機器制作',
    type: '機械',
    clientName: '○○市',
    siteName: '製造工場',
    projectName: '給排水配管納品',
    manager: '佐藤',
    engineer: '杉田次郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-08-20',
    endDate: '2026-08-21',
    isCorins: false,
    amount: 720000,
    progress: 0,
    status: '未着手',
    currentPhase: '納品',
  },
  {
    id: '30',
    orderNo: '38-K05',
    workType: '機器制作',
    type: '電気',
    clientName: '◇◇商業施設',
    siteName: '工場',
    projectName: '照明制御盤製作',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-11-25',
    endDate: '2026-11-25',
    isCorins: false,
    amount: 420000,
    progress: 0,
    status: '未着手',
    currentPhase: '製作',
  },
  {
    id: '31',
    orderNo: '38-K06',
    workType: '機器制作',
    type: '機械',
    clientName: '●●工場',
    siteName: '協力工場',
    projectName: '配管部材製作納品',
    manager: '高橋',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2027-02-18',
    endDate: '2027-02-19',
    isCorins: false,
    amount: 550000,
    progress: 0,
    status: '未着手',
    currentPhase: '納品',
  },
  // タスク割当ステータスのテストデータ（v2.26追加）
  {
    id: '32',
    orderNo: '38-011',
    workType: '工事',
    type: '機械',
    clientName: '▼▼市役所',
    siteName: '下水処理施設',
    projectName: '汚水ポンプ設備更新工事',
    manager: '佐藤',
    engineer: '鈴木一郎',
    contractType: '元',
    exclusive: true,
    startDate: '2025-11-01',
    endDate: '2026-03-31',
    isCorins: true,
    amount: 58000000,
    progress: 0,
    status: 'タスク割当',
    currentPhase: '契約フェーズ',
    partnerIds: ['1'],
  },
  {
    id: '33',
    orderNo: '38-012',
    workType: '工事',
    type: '電気',
    clientName: '◆◆施設',
    siteName: '管理棟',
    projectName: '照明設備LED化工事',
    manager: '高橋',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-10-25',
    endDate: '2025-12-15',
    isCorins: false,
    amount: 18500000,
    progress: 0,
    status: 'タスク割当',
    currentPhase: '契約フェーズ',
    partnerIds: ['2'],
  },
];

// タスクモックデータ（2025年11月5日基準）
export const mockTasks = {
  '1': {
    契約フェーズ: [
      { id: 't1', name: '契約書締結', completed: false, deadline: '2025-11-02', assignee: '田中' },
      { id: 't2', name: 'CORINS登録要否確認', completed: false, deadline: '2025-11-05', assignee: '田中' },
      { id: 't3', name: '現場代理人選任通知', completed: false, deadline: '2025-11-07', assignee: '田中' },
    ],
    着工準備フェーズ: [
      { id: 't4', name: '工程表提出', completed: false, deadline: '2025-11-10', assignee: '田中' },
      { id: 't5', name: '施工計画書作成', completed: false, deadline: '2025-11-15', assignee: '山田太郎' },
      { id: 't6', name: '設計図書照査', completed: false, deadline: '2025-11-18', assignee: '山田太郎' },
    ],
    施工フェーズ: [
      { id: 't7', name: '施工状況報告書', completed: false, deadline: '2025-11-25', assignee: '田中' },
      { id: 't8', name: '工程会議', completed: false, deadline: '2025-11-20', assignee: '山田太郎' },
      { id: 't9', name: '工事写真撮影', completed: false, deadline: '2025-11-28', assignee: '山田太郎' },
    ],
  },
  '2': {
    契約フェーズ: [
      { id: 't21', name: '契約書締結', completed: false, deadline: '2025-11-01', assignee: '佐藤' },
      { id: 't22', name: '現場代理人選任通知', completed: false, deadline: '2025-11-03', assignee: '佐藤' },
    ],
    着工準備フェーズ: [
      { id: 't23', name: '工程表提出', completed: false, deadline: '2025-11-05', assignee: '佐藤' },
      { id: 't24', name: '施工計画書作成', completed: false, deadline: '2025-11-08', assignee: '鈴木一郎' },
      { id: 't25', name: '施工体制台帳作成', completed: false, deadline: '2025-11-12', assignee: '佐藤' },
    ],
  },
  '3': {
    施工フェーズ: [
      { id: 't31', name: '施工状況報告書', completed: false, deadline: '2025-11-04', assignee: '高橋' },
      { id: 't32', name: '工程会議', completed: false, deadline: '2025-11-06', assignee: '伊藤次郎' },
      { id: 't33', name: '工事写真撮影', completed: false, deadline: '2025-11-09', assignee: '伊藤次郎' },
      { id: 't34', name: '安全パトロール', completed: false, deadline: '2025-11-14', assignee: '高橋' },
    ],
  },
  '4': {
    施工フェーズ: [
      { id: 't41', name: '工事写真撮影', completed: false, deadline: '2025-11-05', assignee: '髙峯一郎' },
      { id: 't42', name: '施工状況報告書', completed: false, deadline: '2025-11-11', assignee: '鈴木' },
      { id: 't43', name: '最終確認', completed: false, deadline: '2025-11-28', assignee: '髙峯一郎' },
    ],
  },
  '5': {
    着工準備フェーズ: [
      { id: 't51', name: '工程表提出', completed: false, deadline: '2025-11-05', assignee: '高橋' },
      { id: 't52', name: '施工計画書作成', completed: false, deadline: '2025-11-16', assignee: '杉田次郎' },
    ],
  },
  '6': {
    契約フェーズ: [
      { id: 't61', name: '契約書締結', completed: false, deadline: '2025-11-03', assignee: '田中' },
      { id: 't62', name: 'CORINS登録要否確認', completed: false, deadline: '2025-11-08', assignee: '髙峯一郎' },
    ],
  },
  '7': {
    施工フェーズ: [
      { id: 't71', name: '工程会議', completed: false, deadline: '2025-11-13', assignee: '中村三郎' },
      { id: 't72', name: '工事写真撮影', completed: false, deadline: '2025-11-17', assignee: '中村三郎' },
    ],
  },
  '8': {
    契約フェーズ: [
      { id: 't81', name: '契約書締結', completed: false, deadline: '2025-11-04', assignee: '佐藤' },
      { id: 't82', name: 'CORINS登録（契約）', completed: false, deadline: '2025-11-10', assignee: '髙峯一郎' },
    ],
  },
  '9': {
    着工準備フェーズ: [
      { id: 't91', name: '工程表提出', completed: false, deadline: '2025-11-22', assignee: '鈴木' },
      { id: 't92', name: '施工計画書作成', completed: false, deadline: '2025-11-26', assignee: '杉田次郎' },
    ],
  },
  '10': {
    竣工フェーズ: [
      { id: 't101', name: '完成図書作成', completed: false, deadline: '2025-11-01', assignee: '高橋' },
      { id: 't102', name: '工事写真整理', completed: false, deadline: '2025-11-06', assignee: '山田太郎' },
      { id: 't103', name: '竣工検査申請', completed: false, deadline: '2025-11-19', assignee: '高橋' },
      { id: 't104', name: '最終報告書作成', completed: false, deadline: '2025-11-30', assignee: '山田太郎' },
    ],
  },
};

export const mockStaff = [
  {
    id: 's1',
    employeeId: 'E001',
    name: '山田太郎',
    jobTitle: '課長',
    department: '技術部1課',
    companyPhone: '080-1234-5678',
    companyEmail: 'yamada.taro@doproject.co.jp',
    qualification: '1級電気工事施工管理技士',
    specialty: '電気',
    availability: 100,
    hasAdminPermission: true,
    driverLicenseExpiry: '2025-12-05', // 1ヶ月前アラート表示対象
    qualifications: [
      {
        id: 'q1-1',
        category1: '免許',
        category2: '施工管理技士（１級）',
        qualificationName: '１級電気工事施工管理技士',
        qualificationDetail: '',
        acquisitionDate: '2018-06-15',
        expiryDate: '2025-12-10', // 1ヶ月前アラート表示対象
        customName: ''
      },
      {
        id: 'q1-2',
        category1: '免許',
        category2: '電気工事士',
        qualificationName: '第一種電気工事士免状',
        qualificationDetail: '',
        acquisitionDate: '2015-03-20',
        expiryDate: '2026-03-20',
        customName: ''
      },
      {
        id: 'q1-3',
        category1: '技能講習',
        category2: '作業主任者',
        qualificationName: '足場の組立て等作業主任者',
        qualificationDetail: '',
        acquisitionDate: '2017-09-10',
        expiryDate: '',
        customName: ''
      }
    ]
  },
  {
    id: 's2',
    employeeId: 'E002',
    name: '鈴木一郎',
    jobTitle: '課長補佐',
    department: '技術部1課',
    companyPhone: '080-2345-6789',
    companyEmail: 'suzuki.ichiro@doproject.co.jp',
    qualification: '1級管工事施工管理技士',
    specialty: '機械',
    availability: 80,
    hasAdminPermission: false,
    driverLicenseExpiry: '2025-12-15', // 1ヶ月前アラート表示対象
    qualifications: [
      {
        id: 'q2-1',
        category1: '免許',
        category2: '施工管理技士（１級）',
        qualificationName: '１級管工事施工管理技士',
        qualificationDetail: '',
        acquisitionDate: '2019-07-20',
        expiryDate: '2025-12-18', // 1ヶ月前アラート表示対象
        customName: ''
      },
      {
        id: 'q2-2',
        category1: '労働安全衛生',
        category2: '職長・安全衛生',
        qualificationName: '職長・安全衛生責任者教育修了証',
        qualificationDetail: '',
        acquisitionDate: '2016-05-15',
        expiryDate: '',
        customName: ''
      }
    ]
  },
  {
    id: 's3',
    employeeId: 'E003',
    name: '伊藤次郎',
    jobTitle: '係長',
    department: '技術部2課',
    companyPhone: '080-3456-7890',
    companyEmail: 'ito.jiro@doproject.co.jp',
    qualification: '1級土木施工管理技士',
    specialty: '機械',
    availability: 60,
    hasAdminPermission: false,
    driverLicenseExpiry: '2026-03-20', // アラート対象外
    qualifications: []
  },
  {
    id: 's4',
    employeeId: 'E004',
    name: '田中三郎',
    jobTitle: '主任',
    department: '営業部',
    companyPhone: '080-4567-8901',
    companyEmail: 'tanaka.saburo@doproject.co.jp',
    qualification: '2級電気工事施工管理技士',
    specialty: '電気',
    availability: 100,
    hasAdminPermission: false,
    driverLicenseExpiry: '2026-06-10', // アラート対象外
    qualifications: []
  },
  {
    id: 's5',
    employeeId: 'E005',
    name: '高橋四郎',
    jobTitle: 'メンバー',
    department: '技術部2課',
    companyPhone: '080-5678-9012',
    companyEmail: 'takahashi.shiro@doproject.co.jp',
    qualification: '1級管工事施工管理技士',
    specialty: '機械',
    availability: 40,
    hasAdminPermission: false,
    driverLicenseExpiry: '2027-01-15', // アラート対象外
    qualifications: []
  },
  {
    id: 's6',
    employeeId: 'E006',
    name: '佐藤次郎',
    jobTitle: '部長',
    department: '技術部1課',
    companyPhone: '080-6789-0123',
    companyEmail: 'bucho@example.com',
    qualification: '1級電気工事施工管理技士',
    specialty: '電気',
    availability: 90,
    hasAdminPermission: false,
    driverLicenseExpiry: '2026-09-30', // アラート対象外
    qualifications: []
  },
  {
    id: 's7',
    employeeId: 'E007',
    name: '中村五郎',
    jobTitle: 'メンバー',
    department: '技術部1課',
    companyPhone: '080-7890-1234',
    companyEmail: 'ippan@example.com',
    qualification: '2級管工事施工管理技士',
    specialty: '機械',
    availability: 100,
    hasAdminPermission: false,
    driverLicenseExpiry: '2026-04-25', // アラート対象外
    qualifications: []
  },
  {
    id: 's8',
    employeeId: 'E008',
    name: '田村',
    jobTitle: '主任',
    department: '技術部1課',
    companyPhone: '080-8901-2345',
    companyEmail: 'tamura@doproject.co.jp',
    qualification: '1級管工事施工管理技士',
    specialty: '機械',
    availability: 70,
    hasAdminPermission: false,
    driverLicenseExpiry: '2026-11-05', // アラート対象外
    qualifications: []
  },
];

export const urgentTasks = [
  { id: 'u1', projectName: '中央監視設備更新工事', taskName: '施工体制台帳作成', deadline: '2025-09-20', daysLeft: 2 },
  { id: 'u2', projectName: '中央監視設備更新工事', taskName: '設計図書照査', deadline: '2025-09-18', daysLeft: 0 },
  { id: 'u3', projectName: '受変電設備改修工事', taskName: '工程表提出', deadline: '2025-09-25', daysLeft: 3 },
];

// 個人予定のモックデータ
// 個人予定モックデータ（2025年11月5日基準）
export const mockPersonalEvents = [
  // 11月の予定
  { id: 'e1', title: '月初報告会', date: '2025-11-01', startTime: '09:00', endTime: '10:00', userId: '山田太郎' },
  { id: 'e2', title: '安全衛生会議', date: '2025-11-02', startTime: '10:00', endTime: '11:30', userId: '田中' },
  { id: 'e3', title: '協力会社打ち合わせ', date: '2025-11-03', startTime: '14:00', endTime: '16:00', userId: '田中' },
  { id: 'e4', title: '現場視察', date: '2025-11-04', startTime: '09:00', endTime: '12:00', userId: '山田太郎' },
  { id: 'e5', title: '安全パトロール', date: '2025-11-05', startTime: '09:00', endTime: '11:00', userId: '高橋' },
  { id: 'e6', title: '工程会議', date: '2025-11-05', startTime: '14:00', endTime: '16:00', userId: '山田太郎' },
  { id: 'e7', title: '設計打ち合わせ', date: '2025-11-06', startTime: '10:00', endTime: '12:00', userId: '山田太郎' },
  { id: 'e8', title: '資材検収立会', date: '2025-11-07', startTime: '13:00', endTime: '15:00', userId: '山田太郎' },
  { id: 'e9', title: '協力会社定例会', date: '2025-11-08', startTime: '10:00', endTime: '12:00', userId: '佐藤' },
  { id: 'e10', title: '品質検査', date: '2025-11-10', startTime: '09:00', endTime: '11:00', userId: '山田太郎' },
  { id: 'e11', title: '現場立会検査', date: '2025-11-11', startTime: '10:00', endTime: '15:00', userId: '伊藤次郎' },
  { id: 'e12', title: '安全衛生講習', date: '2025-11-12', startTime: '13:00', endTime: '17:00', userId: '山田太郎' },
  { id: 'e13', title: '技術研修会', date: '2025-11-13', startTime: '09:00', endTime: '12:00', userId: '佐藤' },
  { id: 'e14', title: '施工図確認', date: '2025-11-14', startTime: '14:00', endTime: '16:00', userId: '山田太郎' },
  { id: 'e15', title: '品質管理会議', date: '2025-11-15', startTime: '10:00', endTime: '12:00', userId: '田中' },
  { id: 'e16', title: '資材納品立会', date: '2025-11-17', startTime: '13:00', endTime: '14:30', userId: '山田太郎' },
  { id: 'e17', title: '施工計画検討会', date: '2025-11-18', startTime: '09:30', endTime: '11:30', userId: '山田太郎' },
  { id: 'e18', title: '中間検査', date: '2025-11-19', startTime: '10:00', endTime: '15:00', userId: '山田太郎' },
  { id: 'e19', title: '安全教育', date: '2025-11-20', startTime: '14:00', endTime: '16:00', userId: '高橋' },
  { id: 'e20', title: '工程調整会議', date: '2025-11-21', startTime: '10:00', endTime: '12:00', userId: '佐藤' },
  { id: 'e21', title: '発注者打ち合わせ', date: '2025-11-22', startTime: '13:30', endTime: '15:30', userId: '山田太郎' },
  { id: 'e22', title: '定例会議', date: '2025-11-24', startTime: '15:00', endTime: '17:00', userId: '鈴木' },
  { id: 'e23', title: '工事進捗確認', date: '2025-11-25', startTime: '10:00', endTime: '12:00', userId: '山田太郎' },
  { id: 'e24', title: '品質管理報告', date: '2025-11-26', startTime: '09:00', endTime: '10:30', userId: '山田太郎' },
  { id: 'e25', title: 'ISO監査', date: '2025-11-27', startTime: '09:00', endTime: '12:00', userId: '田中' },
  { id: 'e26', title: '竣工検査準備', date: '2025-11-28', startTime: '14:00', endTime: '17:00', userId: '山田太郎' },
  { id: 'e27', title: '月末締め作業', date: '2025-11-29', startTime: '13:00', endTime: '18:00', userId: '佐藤' },
  { id: 'e28', title: '次月計画立案', date: '2025-11-30', startTime: '09:00', endTime: '11:00', userId: '山田太郎' },
];

// 協力会社モックデータ
export const mockPartners = [
  {
    id: '1',
    companyName: '株式会社山本工業',
    companyNameKana: 'カブシキガイシャヤマモトコウギョウ',
    representative: '山本太郎',
    address: '東京都千代田区丸の内1-1-1',
    phone: '03-1234-5678',
    email: 'info@yamamoto-kogyo.co.jp',
    notes: '機械設備工事を得意とする協力会社。実績多数。',
    displayColor: '#DC2626', // 赤色
    registeredDate: '2020-04-01',
    updatedDate: '2025-09-15',
  },
  {
    id: '2',
    companyName: '田中電気工業株式会社',
    companyNameKana: 'タナカデンキコウギョウカブシキガイシャ',
    representative: '田中一郎',
    address: '神奈川県横浜市西区みなとみらい2-2-2',
    phone: '045-2345-6789',
    email: 'contact@tanaka-denki.co.jp',
    notes: '電気工事専門。受変電設備に強み。',
    displayColor: '#2563EB', // 青色
    registeredDate: '2019-06-15',
    updatedDate: '2025-08-20',
  },
  {
    id: '3',
    companyName: '佐藤建設株式会社',
    companyNameKana: 'サトウケンセツカブシキガイシャ',
    representative: '佐藤健二',
    address: '埼玉県さいたま市大宮区桜木町3-3-3',
    phone: '048-3456-7890',
    email: 'info@sato-kensetsu.jp',
    notes: '鋼構造物工事が専門。大型案件対応可能。',
    displayColor: '#16A34A', // 緑色
    registeredDate: '2018-03-01',
    updatedDate: '2025-09-01',
  },
  {
    id: '4',
    companyName: '鈴木通信工業',
    companyNameKana: 'スズキツウシンコウギョウ',
    representative: '鈴木三郎',
    address: '千葉県千葉市中央区中央4-4-4',
    phone: '043-4567-8901',
    email: 'suzuki@suzuki-tsushin.com',
    notes: '通信設備設置・保守に特化。迅速対応が強み。',
    displayColor: '', // 未設定（グレー表示）
    registeredDate: '2021-01-20',
    updatedDate: '2025-07-10',
  },
  {
    id: '5',
    companyName: '高橋設備株式会社',
    companyNameKana: 'タカハシセツビカブシキガイシャ',
    representative: '高橋花子',
    address: '東京都新宿区西新宿5-5-5',
    phone: '03-5678-9012',
    email: 'info@takahashi-setsubi.co.jp',
    notes: '給排水・空調設備工事全般対応可能。',
    displayColor: '#EA580C', // オレンジ色
    registeredDate: '2017-09-10',
    updatedDate: '2025-09-20',
  },
  {
    id: '6',
    companyName: '伊藤製作所',
    companyNameKana: 'イトウセイサクショ',
    representative: '伊藤五郎',
    address: '神奈川県川崎市川崎区東田町6-6-6',
    phone: '044-6789-0123',
    email: 'ito@ito-seisakusho.com',
    notes: '機器制作に特化。カスタム制作対応可能。',
    displayColor: '#9333EA', // 紫色
    registeredDate: '2020-11-05',
    updatedDate: '2025-08-30',
  },
  {
    id: '7',
    companyName: '渡辺メンテナンス',
    companyNameKana: 'ワタナベメンテナンス',
    representative: '渡辺六郎',
    address: '東京都品川区大崎7-7-7',
    phone: '03-7890-1234',
    email: 'watanabe@watanabe-maintenance.jp',
    notes: '保守点検業務専門。定期点検契約多数。',
    displayColor: '', // 未設定（グレー表示）
    registeredDate: '2019-02-14',
    updatedDate: '2025-09-10',
  },
];

// 協力会社書類モックデータ
export const mockPartnerDocuments = [
  { id: 'd1', partnerId: '1', fileName: '会社概要_山本工業.pdf', filePath: '/documents/partner1/company_profile.pdf', fileSize: 1024000, uploadedDate: '2025-09-15' },
  { id: 'd2', partnerId: '1', fileName: '保険証券_2025.pdf', filePath: '/documents/partner1/insurance_2025.pdf', fileSize: 512000, uploadedDate: '2025-09-15' },
  { id: 'd3', partnerId: '2', fileName: '会社案内_田中電気.pdf', filePath: '/documents/partner2/company_guide.pdf', fileSize: 2048000, uploadedDate: '2025-08-20' },
  { id: 'd4', partnerId: '3', fileName: '営業許可証_佐藤建設.pdf', filePath: '/documents/partner3/business_license.pdf', fileSize: 768000, uploadedDate: '2025-09-01' },
  { id: 'd5', partnerId: '5', fileName: '施工実績書.xlsx', filePath: '/documents/partner5/track_record.xlsx', fileSize: 256000, uploadedDate: '2025-09-20' },
];

// 【v2.26】システム内通知モックデータ
export const mockNotifications = [
  {
    id: 'n1',
    userId: '佐藤',
    projectId: '32',
    message: '新規案件「汚水ポンプ設備更新工事」のタスク割り当てを依頼されました。',
    type: 'task_assignment',
    createdAt: '2025-10-17T10:00:00',
    isRead: false,
  },
  {
    id: 'n2',
    userId: '高橋',
    projectId: '33',
    message: '新規案件「照明設備LED化工事」のタスク割り当てを依頼されました。',
    type: 'task_assignment',
    createdAt: '2025-10-17T10:05:00',
    isRead: false,
  },
];

// 全体予定（会社休日・出勤日設定）モックデータ
export const mockCompanyHolidays: Array<{
  id: string;
  date: string;
  type: 'holiday' | 'workday';
  memo?: string;
  createdBy: string;
}> = [];