// モックデータ
export const mockProjects = [
  {
    id: '1',
    orderNo: '37-098',
    workType: '工事',
    type: '機械',
    clientName: '○○建設',
    siteName: '○○浄化センター',
    projectName: '中央監視設備更新工事',
    manager: '田中',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-09-01',
    endDate: '2026-02-28',
    isCorins: true,
    amount: 45000000,
    progress: 35,
    status: '施工中',
    currentPhase: '施工フェーズ',
    partnerId: '1', // 株式会社山本工業
  },
  {
    id: '2',
    orderNo: '37-099',
    workType: '工事',
    type: '電気',
    clientName: '△△工業',
    siteName: '△△ポンプ場',
    projectName: '受変電設備改修工事',
    manager: '佐藤',
    engineer: '鈴木一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-15',
    endDate: '2025-11-30',
    isCorins: false,
    amount: 8500000,
    progress: 0,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '3',
    orderNo: '37-100',
    workType: '工事',
    type: '機械',
    clientName: '□□市役所',
    siteName: '□□処理場',
    projectName: 'ポンプ設備更新工事',
    manager: '高橋',
    engineer: '伊藤次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2025-10-01',
    endDate: '2026-04-30',
    isCorins: true,
    amount: 125000000,
    progress: 45,
    status: '施工中',
    currentPhase: '施工フェーズ',
    partnerId: '3', // 佐藤建設株式会社
  },
  {
    id: '4',
    orderNo: '37-101',
    workType: '工事',
    type: '電気',
    clientName: '××病院',
    siteName: '新館',
    projectName: 'LED照明更新',
    manager: '鈴木',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-20',
    endDate: '2025-10-31',
    isCorins: false,
    amount: 8500000,
    progress: 60,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '5',
    orderNo: '37-102',
    workType: '工事',
    type: '機械',
    clientName: '▽▽ビル',
    siteName: '地下機械室',
    projectName: 'ボイラー更新工事',
    manager: '高橋',
    engineer: '杉田次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2025-11-01',
    endDate: '2026-01-31',
    isCorins: true,
    amount: 38000000,
    progress: 25,
    status: '施工中',
    partnerId: '2', // 田中電気工業株式会社
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '6',
    orderNo: '38-002',
    workType: '工事',
    type: '電気',
    clientName: '○○学校',
    siteName: '体育館',
    projectName: '音響設備改修',
    manager: '田中',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-12-01',
    endDate: '2026-01-15',
    isCorins: false,
    amount: 12000000,
    progress: 10,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '7',
    orderNo: '37-103',
    workType: '工事',
    type: '機械',
    clientName: '△△ホテル',
    siteName: '本館',
    projectName: 'エレベーター改修',
    manager: '山田',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-25',
    endDate: '2025-10-31',
    isCorins: false,
    amount: 25000000,
    progress: 75,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '8',
    orderNo: '38-003',
    workType: '工事',
    type: '電気',
    clientName: '◎◎工場',
    siteName: '第1プラント',
    projectName: '動力盤更新',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: true,
    startDate: '2026-01-01',
    endDate: '2026-05-31',
    isCorins: true,
    amount: 48000000,
    progress: 5,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '9',
    orderNo: '37-104',
    workType: '工事',
    type: '機械',
    clientName: '▲▲マンション',
    siteName: '共用部',
    projectName: '給水ポンプ交換',
    manager: '鈴木',
    engineer: '杉田次郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-10-10',
    endDate: '2025-11-15',
    isCorins: false,
    amount: 5500000,
    progress: 20,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '10',
    orderNo: '37-105',
    workType: '工事',
    type: '電気',
    clientName: '■■商業施設',
    siteName: 'B館',
    projectName: '防災設備更新',
    manager: '高橋',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-09-05',
    endDate: '2025-10-20',
    isCorins: false,
    amount: 15000000,
    progress: 90,
    status: '施工中',
    currentPhase: '竣工フェーズ',
  },
  {
    id: '11',
    orderNo: '38-004',
    workType: '工事',
    type: '機械',
    clientName: '☆☆病院',
    siteName: '本館',
    projectName: '空調設備改修',
    manager: '田中',
    engineer: '中村三郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-02-01',
    endDate: '2026-05-31',
    isCorins: false,
    amount: 32000000,
    progress: 30,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '12',
    orderNo: '37-106',
    workType: '工事',
    type: '電気',
    clientName: '◇◇工業',
    siteName: '第2工場',
    projectName: '受変電設備改修',
    manager: '山田',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-03-01',
    endDate: '2026-05-31',
    isCorins: false,
    amount: 15000000,
    progress: 50,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '13',
    orderNo: '38-005',
    workType: '工事',
    type: '機械',
    clientName: '○○市',
    siteName: '市民会館',
    projectName: '給排水設備更新',
    manager: '佐藤',
    engineer: '杉田次郎',
    contractType: '元',
    exclusive: true,
    startDate: '2026-01-15',
    endDate: '2026-07-31',
    isCorins: true,
    amount: 65000000,
    progress: 0,
    status: '契約済',
    currentPhase: '契約フェーズ',
  },
  {
    id: '14',
    orderNo: '37-107',
    workType: '工事',
    type: '電気',
    clientName: '△△大学',
    siteName: '研究棟',
    projectName: '実験設備電源工事',
    manager: '鈴木',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-04-01',
    endDate: '2026-07-15',
    isCorins: false,
    amount: 22000000,
    progress: 15,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '15',
    orderNo: '38-006',
    workType: '工事',
    type: '機械',
    clientName: '××ビル',
    siteName: '屋上',
    projectName: '冷却塔更新',
    manager: '高橋',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-15',
    endDate: '2025-12-24',
    isCorins: false,
    amount: 9800000,
    progress: 55,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '16',
    orderNo: '38-007',
    workType: '工事',
    type: '鋼造',
    clientName: '○○建設',
    siteName: '新築現場',
    projectName: '鉄骨構造物組立工事',
    manager: '田中',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    isCorins: true,
    amount: 75000000,
    progress: 20,
    status: '施工中',
    currentPhase: '着工準備フェーズ',
  },
  {
    id: '17',
    orderNo: '38-008',
    workType: '工事',
    type: '通信',
    clientName: '△△通信',
    siteName: '基地局',
    projectName: '通信設備設置工事',
    manager: '佐藤',
    engineer: '鈴木一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-20',
    endDate: '2025-11-15',
    isCorins: false,
    amount: 18000000,
    progress: 45,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  {
    id: '18',
    orderNo: '38-009',
    workType: '工事',
    type: '納品',
    clientName: '□□商事',
    siteName: '倉庫',
    projectName: '機械設備納品',
    manager: '高橋',
    engineer: '伊藤次郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-10-05',
    endDate: '2025-10-20',
    isCorins: false,
    amount: 12000000,
    progress: 80,
    status: '施工中',
    currentPhase: '竣工フェーズ',
  },
  {
    id: '19',
    orderNo: '38-010',
    workType: '工事',
    type: 'その他',
    clientName: '××企業',
    siteName: '本社',
    projectName: '特殊設備メンテナンス',
    manager: '鈴木',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-09-10',
    endDate: '2025-10-31',
    isCorins: false,
    amount: 8500000,
    progress: 60,
    status: '施工中',
    currentPhase: '施工フェーズ',
  },
  // 保守点検（スポット案件 - 月内1〜2日、3ヶ月に1回程度）
  {
    id: '20',
    orderNo: '38-M01',
    workType: '保守点検',
    type: '機械',
    clientName: '○○浄化センター',
    siteName: '中央監視室',
    projectName: '中央監視設備定期点検',
    manager: '田中',
    engineer: '山田太郎',
    contractType: '元',
    exclusive: false,
    startDate: '2025-10-20',
    endDate: '2025-10-21',
    isCorins: false,
    amount: 250000,
    progress: 100,
    status: '完了',
    currentPhase: '点検',
  },
  {
    id: '21',
    orderNo: '38-M02',
    workType: '保守点検',
    type: '電気',
    clientName: '△△ポンプ場',
    siteName: '受変電室',
    projectName: '受変電設備年次点検',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-01-15',
    endDate: '2026-01-16',
    isCorins: false,
    amount: 180000,
    progress: 0,
    status: '未着手',
    currentPhase: '点検',
  },
  {
    id: '22',
    orderNo: '38-M03',
    workType: '保守点検',
    type: '機械',
    clientName: '□□処理場',
    siteName: 'ポンプ棟',
    projectName: 'ポンプ設備定期保守',
    manager: '高橋',
    engineer: '伊藤次郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-04-22',
    endDate: '2026-04-22',
    isCorins: false,
    amount: 320000,
    progress: 0,
    status: '未着手',
    currentPhase: '保守',
  },
  {
    id: '23',
    orderNo: '38-M04',
    workType: '保守点検',
    type: '電気',
    clientName: '◎◎工場',
    siteName: '第1プラント',
    projectName: '動力盤定期点検',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-07-10',
    endDate: '2026-07-10',
    isCorins: false,
    amount: 150000,
    progress: 0,
    status: '未着手',
    currentPhase: '点検',
  },
  {
    id: '28',
    orderNo: '38-M05',
    workType: '保守点検',
    type: '機械',
    clientName: '▲▲施設',
    siteName: '空調機械室',
    projectName: '空調設備定期点検',
    manager: '田中',
    engineer: '中村三郎',
    contractType: '元',
    exclusive: false,
    startDate: '2026-10-25',
    endDate: '2026-10-25',
    isCorins: false,
    amount: 200000,
    progress: 0,
    status: '未着手',
    currentPhase: '点検',
  },
  {
    id: '29',
    orderNo: '38-M06',
    workType: '保守点検',
    type: '電気',
    clientName: '■■センター',
    siteName: '電気室',
    projectName: '非常用発電機点検',
    manager: '高橋',
    engineer: '髙峯一郎',
    contractType: '元',
    exclusive: false,
    startDate: '2027-01-20',
    endDate: '2027-01-21',
    isCorins: false,
    amount: 280000,
    progress: 0,
    status: '未着手',
    currentPhase: '点検',
  },
  // 機器制作（スポット案件 - 月内1〜2日、3ヶ月に1回程度）
  {
    id: '24',
    orderNo: '38-K01',
    workType: '機器制作',
    type: '機械',
    clientName: '▽▽ビル',
    siteName: '機械工場',
    projectName: 'ボイラー部品製作',
    manager: '高橋',
    engineer: '杉田次郎',
    contractType: '下',
    exclusive: false,
    startDate: '2025-11-18',
    endDate: '2025-11-19',
    isCorins: false,
    amount: 450000,
    progress: 50,
    status: '施工中',
    currentPhase: '製作',
  },
  {
    id: '25',
    orderNo: '38-K02',
    workType: '機器制作',
    type: '電気',
    clientName: '○○学校',
    siteName: '工場',
    projectName: '音響設備制御盤製作',
    manager: '田中',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-02-05',
    endDate: '2026-02-06',
    isCorins: false,
    amount: 680000,
    progress: 0,
    status: '未着手',
    currentPhase: '製作',
  },
  {
    id: '26',
    orderNo: '38-K03',
    workType: '機器制作',
    type: '機械',
    clientName: '☆☆病院',
    siteName: '協力工場',
    projectName: '空調設備ダクト製作',
    manager: '田中',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-05-12',
    endDate: '2026-05-12',
    isCorins: false,
    amount: 580000,
    progress: 0,
    status: '未着手',
    currentPhase: '製作',
  },
  {
    id: '27',
    orderNo: '38-K04',
    workType: '機器制作',
    type: '機械',
    clientName: '○○市',
    siteName: '製造工場',
    projectName: '給排水配管納品',
    manager: '佐藤',
    engineer: '杉田次郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-08-20',
    endDate: '2026-08-21',
    isCorins: false,
    amount: 720000,
    progress: 0,
    status: '未着手',
    currentPhase: '納品',
  },
  {
    id: '30',
    orderNo: '38-K05',
    workType: '機器制作',
    type: '電気',
    clientName: '◇◇商業施設',
    siteName: '工場',
    projectName: '照明制御盤製作',
    manager: '佐藤',
    engineer: '髙峯一郎',
    contractType: '下',
    exclusive: false,
    startDate: '2026-11-25',
    endDate: '2026-11-25',
    isCorins: false,
    amount: 420000,
    progress: 0,
    status: '未着手',
    currentPhase: '製作',
  },
  {
    id: '31',
    orderNo: '38-K06',
    workType: '機器制作',
    type: '機械',
    clientName: '●●工場',
    siteName: '協力工場',
    projectName: '配管部材製作納品',
    manager: '高橋',
    engineer: '中村三郎',
    contractType: '下',
    exclusive: false,
    startDate: '2027-02-18',
    endDate: '2027-02-19',
    isCorins: false,
    amount: 550000,
    progress: 0,
    status: '未着手',
    currentPhase: '納品',
  },
];

export const mockTasks = {
  '1': {
    契約フェーズ: [
      { id: 't1', name: '契約書締結', completed: false, deadline: '2025-09-05', assignee: '田中' },
      { id: 't2', name: 'CORINS登録要否確認', completed: false, deadline: '2025-09-06', assignee: '田中' },
      { id: 't3', name: '現場代理人選任通知', completed: false, deadline: '2025-09-07', assignee: '田中' },
      { id: 't4', name: '主任技術者選任通知', completed: false, deadline: '2025-09-07', assignee: '田中' },
      { id: 't5', name: 'CORINS登録（契約）', completed: false, deadline: '2025-09-08', assignee: '田中' },
    ],
    着工準備フェーズ: [
      { id: 't6', name: '工程表提出', completed: false, deadline: '2025-09-10', assignee: '田中' },
      { id: 't7', name: '施工計画書作成', completed: false, deadline: '2025-09-15', assignee: '山田太郎' },
      { id: 't8', name: '施工体制台帳作成', completed: false, deadline: '2025-09-20', assignee: '田中' },
      { id: 't9', name: '設計図書照査', completed: false, deadline: '2025-09-18', assignee: '山田太郎' },
    ],
    施工フェーズ: [
      { id: 't10', name: '施工状況報告書', completed: false, deadline: '2025-09-30', assignee: '田中' },
      { id: 't11', name: '工程会議', completed: false, deadline: '2025-09-25', assignee: '山田太郎' },
      { id: 't12', name: '工事写真撮影', completed: false, deadline: '2025-09-28', assignee: '山田太郎' },
      { id: 't13', name: '施工状況報告書', completed: false, deadline: '2025-10-31', assignee: '田中' },
      { id: 't14', name: '工程会議', completed: false, deadline: '2025-10-15', assignee: '山田太郎' },
      { id: 't15', name: '工事写真撮影', completed: false, deadline: '2025-10-20', assignee: '山田太郎' },
      { id: 't16', name: '中間検査準備', completed: false, deadline: '2025-10-10', assignee: '田中' },
      { id: 't17', name: '安全管理報告', completed: false, deadline: '2025-10-06', assignee: '山田太郎' },
    ],
  },
  '2': {
    契約フェーズ: [
      { id: 't21', name: '契約書締結', completed: false, deadline: '2025-09-10', assignee: '佐藤' },
      { id: 't22', name: '現場代理人選任通知', completed: false, deadline: '2025-09-12', assignee: '佐藤' },
      { id: 't23', name: '主任技術者選任通知', completed: false, deadline: '2025-09-12', assignee: '鈴木一郎' },
    ],
    着工準備フェーズ: [
      { id: 't24', name: '工程表提出', completed: false, deadline: '2025-10-05', assignee: '佐藤' },
      { id: 't25', name: '施工計画書作成', completed: false, deadline: '2025-10-08', assignee: '鈴木一郎' },
      { id: 't26', name: '施工体制台帳作成', completed: false, deadline: '2025-10-12', assignee: '佐藤' },
    ],
  },
  '3': {
    施工フェーズ: [
      { id: 't31', name: '施工状況報告書', completed: false, deadline: '2025-09-15', assignee: '高橋' },
      { id: 't32', name: '工程会議', completed: false, deadline: '2025-09-20', assignee: '伊藤次郎' },
      { id: 't33', name: '工事写真撮影', completed: false, deadline: '2025-09-22', assignee: '伊藤次郎' },
      { id: 't34', name: '施工状況報告書', completed: false, deadline: '2025-10-25', assignee: '高橋' },
      { id: 't35', name: '工程会議', completed: false, deadline: '2025-10-18', assignee: '伊藤次郎' },
      { id: 't36', name: '安全パトロール', completed: false, deadline: '2025-10-07', assignee: '高橋' },
    ],
  },
  '4': {
    施工フェーズ: [
      { id: 't41', name: '工事写真撮影', completed: false, deadline: '2025-09-08', assignee: '髙峯一郎' },
      { id: 't42', name: '施工状況報告書', completed: false, deadline: '2025-09-10', assignee: '鈴木' },
      { id: 't43', name: '最終確認', completed: false, deadline: '2025-10-28', assignee: '髙峯一郎' },
      { id: 't44', name: '竣工検査', completed: false, deadline: '2025-10-30', assignee: '鈴木' },
    ],
  },
  '5': {
    着工準備フェーズ: [
      { id: 't51', name: '工程表提出', completed: false, deadline: '2025-09-14', assignee: '高橋' },
      { id: 't52', name: '施工計画書作成', completed: false, deadline: '2025-09-16', assignee: '杉田次郎' },
    ],
  },
  '6': {
    契約フェーズ: [
      { id: 't61', name: '契約書締結', completed: false, deadline: '2025-09-18', assignee: '田中' },
      { id: 't62', name: 'CORINS登録要否確認', completed: false, deadline: '2025-09-19', assignee: '髙峯一郎' },
    ],
  },
  '7': {
    施工フェーズ: [
      { id: 't71', name: '工程会議', completed: false, deadline: '2025-09-13', assignee: '中村三郎' },
      { id: 't72', name: '工事写真撮影', completed: false, deadline: '2025-09-17', assignee: '中村三郎' },
    ],
  },
  '8': {
    契約フェーズ: [
      { id: 't81', name: '契約書締結', completed: false, deadline: '2025-09-20', assignee: '佐藤' },
      { id: 't82', name: 'CORINS登録（契約）', completed: false, deadline: '2025-09-22', assignee: '髙峯一郎' },
    ],
  },
  '9': {
    着工準備フェーズ: [
      { id: 't91', name: '工程表提出', completed: false, deadline: '2025-09-24', assignee: '鈴木' },
      { id: 't92', name: '施工計画書作成', completed: false, deadline: '2025-09-26', assignee: '杉田次郎' },
    ],
  },
  '10': {
    竣工フェーズ: [
      { id: 't101', name: '完成図書作成', completed: false, deadline: '2025-09-15', assignee: '高橋' },
      { id: 't102', name: '工事写真整理', completed: false, deadline: '2025-09-17', assignee: '山田太郎' },
      { id: 't103', name: '竣工検査申請', completed: false, deadline: '2025-09-19', assignee: '高橋' },
      { id: 't104', name: '竣工検査立会', completed: false, deadline: '2025-09-20', assignee: '山田太郎' },
      { id: 't105', name: '最終報告書作成', completed: false, deadline: '2025-10-18', assignee: '山田太郎' },
    ],
  },
  '11': {
    施工フェーズ: [
      { id: 't111', name: '機器据付開始', completed: false, deadline: '2025-09-13', assignee: '中村三郎' },
      { id: 't112', name: '配管接続作業', completed: false, deadline: '2025-09-18', assignee: '中村三郎' },
      { id: 't113', name: '中間検査', completed: false, deadline: '2025-09-25', assignee: '田中' },
      { id: 't114', name: '試運転調整', completed: false, deadline: '2025-09-30', assignee: '中村三郎' },
    ],
  },
  '12': {
    施工フェーズ: [
      { id: 't121', name: '既設機器撤去', completed: false, deadline: '2025-09-07', assignee: '髙峯一郎' },
      { id: 't122', name: '新設機器搬入', completed: false, deadline: '2025-09-10', assignee: '髙峯一郎' },
      { id: 't123', name: '配線工事', completed: false, deadline: '2025-09-15', assignee: '髙峯一郎' },
      { id: 't124', name: '動作確認', completed: false, deadline: '2025-09-20', assignee: '山田' },
    ],
  },
  '13': {
    契約フェーズ: [
      { id: 't131', name: '契約書締結', completed: false, deadline: '2025-09-25', assignee: '佐藤' },
      { id: 't132', name: 'CORINS登録要否確認', completed: false, deadline: '2025-09-26', assignee: '佐藤' },
      { id: 't133', name: '現場代理人選任通知', completed: false, deadline: '2025-09-27', assignee: '杉田次郎' },
      { id: 't134', name: '主任技術者選任通知', completed: false, deadline: '2025-09-27', assignee: '杉田次郎' },
      { id: 't135', name: 'CORINS登録（契約）', completed: false, deadline: '2025-09-28', assignee: '佐藤' },
    ],
  },
  '14': {
    着工準備フェーズ: [
      { id: 't141', name: '現場調査', completed: false, deadline: '2025-09-16', assignee: '山田太郎' },
      { id: 't142', name: '設計図書照査', completed: false, deadline: '2025-09-18', assignee: '山田太郎' },
      { id: 't143', name: '工程表作成', completed: false, deadline: '2025-09-20', assignee: '鈴木' },
      { id: 't144', name: '施工計画書作成', completed: false, deadline: '2025-09-22', assignee: '鈴木' },
      { id: 't145', name: '資材発注', completed: false, deadline: '2025-10-05', assignee: '山田太郎' },
      { id: 't146', name: '協力会社選定', completed: false, deadline: '2025-10-12', assignee: '山田太郎' },
    ],
  },
  '15': {
    施工フェーズ: [
      { id: 't151', name: '既設冷却塔解体', completed: false, deadline: '2025-09-09', assignee: '中村三郎' },
      { id: 't152', name: '基礎補強工事', completed: false, deadline: '2025-09-12', assignee: '中村三郎' },
      { id: 't153', name: '新設冷却塔据付', completed: false, deadline: '2025-09-16', assignee: '中村三郎' },
      { id: 't154', name: '配管接続・試運転', completed: false, deadline: '2025-09-20', assignee: '高橋' },
      { id: 't155', name: '完了検査', completed: false, deadline: '2025-09-24', assignee: '高橋' },
    ],
  },
  '16': {
    着工準備フェーズ: [
      { id: 't161', name: '施工計画書作成', completed: false, deadline: '2025-10-08', assignee: '山田太郎' },
      { id: 't162', name: '安全管理計画書', completed: false, deadline: '2025-10-14', assignee: '山田太郎' },
      { id: 't163', name: '工程表提出', completed: false, deadline: '2025-10-20', assignee: '田中' },
      { id: 't164', name: '資材発注計画', completed: false, deadline: '2025-10-25', assignee: '山田太郎' },
    ],
  },
};

export const mockStaff = [
  { id: 's1', name: '山田太郎', qualification: '1級電気工事施工管理技士', specialty: '電気', availability: 100 },
  { id: 's2', name: '鈴木一郎', qualification: '1級管工事施工管理技士', specialty: '機械', availability: 80 },
  { id: 's3', name: '伊藤次郎', qualification: '1級土木施工管理技士', specialty: '機械', availability: 60 },
  { id: 's4', name: '田中三郎', qualification: '2級電気工事施工管理技士', specialty: '電気', availability: 100 },
  { id: 's5', name: '高橋四郎', qualification: '1級管工事施工管理技士', specialty: '機械', availability: 40 },
];

export const urgentTasks = [
  { id: 'u1', projectName: '中央監視設備更新工事', taskName: '施工体制台帳作成', deadline: '2025-09-20', daysLeft: 2 },
  { id: 'u2', projectName: '中央監視設備更新工事', taskName: '設計図書照査', deadline: '2025-09-18', daysLeft: 0 },
  { id: 'u3', projectName: '受変電設備改修工事', taskName: '工程表提出', deadline: '2025-09-25', daysLeft: 3 },
];

// 個人予定のモックデータ
export const mockPersonalEvents = [
  // 9月の予定
  { id: 'e1', title: '安全衛生会議', date: '2025-09-05', startTime: '10:00', endTime: '11:30', userId: '田中' },
  { id: 'e2', title: '協力会社打ち合わせ', date: '2025-09-10', startTime: '14:00', endTime: '16:00', userId: '田中' },
  { id: 'e3', title: '現場視察', date: '2025-09-15', startTime: '09:00', endTime: '12:00', userId: '山田太郎' },
  { id: 'e4', title: '技術研修会', date: '2025-09-20', startTime: '13:00', endTime: '17:00', userId: '佐藤' },
  { id: 'e5', title: '定期健康診断', date: '2025-09-25', startTime: '09:00', endTime: '11:00', userId: '高橋' },
  { id: 'e24', title: '月初報告会', date: '2025-09-02', startTime: '09:00', endTime: '10:00', userId: '山田太郎' },
  { id: 'e25', title: '工程打ち合わせ', date: '2025-09-08', startTime: '13:00', endTime: '15:00', userId: '山田太郎' },
  { id: 'e26', title: '資材検収立会', date: '2025-09-12', startTime: '10:00', endTime: '11:30', userId: '山田太郎' },
  { id: 'e27', title: '品質検査', date: '2025-09-22', startTime: '14:00', endTime: '16:00', userId: '山田太郎' },
  { id: 'e28', title: '安全衛生講習', date: '2025-09-27', startTime: '09:30', endTime: '12:00', userId: '山田太郎' },

  // 10月の予定
  { id: 'e6', title: '月次報告会議', date: '2025-10-01', startTime: '10:00', endTime: '12:00', userId: '田中' },
  { id: 'e7', title: '安全パトロール', date: '2025-10-03', startTime: '09:00', endTime: '11:00', userId: '高橋' },
  { id: 'e8', title: '協力会社安全大会', date: '2025-10-05', startTime: '13:30', endTime: '16:30', userId: '佐藤' },
  { id: 'e9', title: '設計打ち合わせ', date: '2025-10-08', startTime: '14:00', endTime: '16:00', userId: '山田太郎' },
  { id: 'e10', title: '現場立会検査', date: '2025-10-10', startTime: '10:00', endTime: '15:00', userId: '伊藤次郎' },
  { id: 'e11', title: '資材発注会議', date: '2025-10-12', startTime: '10:30', endTime: '12:00', userId: '鈴木' },
  { id: 'e12', title: '品質管理会議', date: '2025-10-15', startTime: '13:00', endTime: '15:00', userId: '田中' },
  { id: 'e13', title: '施工計画検討会', date: '2025-10-18', startTime: '09:30', endTime: '11:30', userId: '山田太郎' },
  { id: 'e14', title: '安全教育', date: '2025-10-20', startTime: '14:00', endTime: '16:00', userId: '高橋' },
  { id: 'e15', title: '工程会議', date: '2025-10-22', startTime: '10:00', endTime: '12:00', userId: '佐藤' },
  { id: 'e16', title: '定例会議', date: '2025-10-25', startTime: '15:00', endTime: '17:00', userId: '鈴木' },
  { id: 'e17', title: 'ISO監査', date: '2025-10-28', startTime: '09:00', endTime: '12:00', userId: '田中' },
  { id: 'e18', title: '月末締め作業', date: '2025-10-31', startTime: '13:00', endTime: '18:00', userId: '佐藤' },
  { id: 'e19', title: '技術勉強会', date: '2025-10-04', startTime: '16:00', endTime: '18:00', userId: '山田太郎' },
  { id: 'e20', title: '現場安全パトロール', date: '2025-10-11', startTime: '09:00', endTime: '12:00', userId: '山田太郎' },
  { id: 'e21', title: '発注者打ち合わせ', date: '2025-10-17', startTime: '13:30', endTime: '15:30', userId: '山田太郎' },
  { id: 'e22', title: '工事進捗確認', date: '2025-10-24', startTime: '10:00', endTime: '12:00', userId: '山田太郎' },
  { id: 'e23', title: '竣工検査準備', date: '2025-10-29', startTime: '14:00', endTime: '17:00', userId: '山田太郎' },

  // 山田太郎さんの10月の予定を追加
  { id: 'e29', title: '月初会議', date: '2025-10-01', startTime: '09:00', endTime: '10:30', userId: '山田太郎' },
  { id: 'e30', title: '工事写真整理', date: '2025-10-02', startTime: '13:00', endTime: '15:00', userId: '山田太郎' },
  { id: 'e31', title: '安全衛生委員会', date: '2025-10-07', startTime: '14:00', endTime: '16:00', userId: '山田太郎' },
  { id: 'e32', title: '協力会社定例会', date: '2025-10-09', startTime: '10:00', endTime: '12:00', userId: '山田太郎' },
  { id: 'e33', title: '施工図確認', date: '2025-10-14', startTime: '09:30', endTime: '11:00', userId: '山田太郎' },
  { id: 'e34', title: '資材納品立会', date: '2025-10-16', startTime: '13:00', endTime: '14:30', userId: '山田太郎' },
  { id: 'e35', title: '中間検査', date: '2025-10-21', startTime: '10:00', endTime: '15:00', userId: '山田太郎' },
  { id: 'e36', title: '工程調整会議', date: '2025-10-23', startTime: '14:00', endTime: '16:00', userId: '山田太郎' },
  { id: 'e37', title: '品質管理報告', date: '2025-10-26', startTime: '09:00', endTime: '10:30', userId: '山田太郎' },
  { id: 'e38', title: '次月計画立案', date: '2025-10-30', startTime: '13:00', endTime: '15:00', userId: '山田太郎' },
];

// 協力会社モックデータ
export const mockPartners = [
  {
    id: '1',
    companyName: '株式会社山本工業',
    companyNameKana: 'カブシキガイシャヤマモトコウギョウ',
    representative: '山本太郎',
    address: '東京都千代田区丸の内1-1-1',
    phone: '03-1234-5678',
    email: 'info@yamamoto-kogyo.co.jp',
    notes: '機械設備工事を得意とする協力会社。実績多数。',
    registeredDate: '2020-04-01',
    updatedDate: '2025-09-15',
  },
  {
    id: '2',
    companyName: '田中電気工業株式会社',
    companyNameKana: 'タナカデンキコウギョウカブシキガイシャ',
    representative: '田中一郎',
    address: '神奈川県横浜市西区みなとみらい2-2-2',
    phone: '045-2345-6789',
    email: 'contact@tanaka-denki.co.jp',
    notes: '電気工事専門。受変電設備に強み。',
    registeredDate: '2019-06-15',
    updatedDate: '2025-08-20',
  },
  {
    id: '3',
    companyName: '佐藤建設株式会社',
    companyNameKana: 'サトウケンセツカブシキガイシャ',
    representative: '佐藤健二',
    address: '埼玉県さいたま市大宮区桜木町3-3-3',
    phone: '048-3456-7890',
    email: 'info@sato-kensetsu.jp',
    notes: '鋼構造物工事が専門。大型案件対応可能。',
    registeredDate: '2018-03-01',
    updatedDate: '2025-09-01',
  },
  {
    id: '4',
    companyName: '鈴木通信工業',
    companyNameKana: 'スズキツウシンコウギョウ',
    representative: '鈴木三郎',
    address: '千葉県千葉市中央区中央4-4-4',
    phone: '043-4567-8901',
    email: 'suzuki@suzuki-tsushin.com',
    notes: '通信設備設置・保守に特化。迅速対応が強み。',
    registeredDate: '2021-01-20',
    updatedDate: '2025-07-10',
  },
  {
    id: '5',
    companyName: '高橋設備株式会社',
    companyNameKana: 'タカハシセツビカブシキガイシャ',
    representative: '高橋花子',
    address: '東京都新宿区西新宿5-5-5',
    phone: '03-5678-9012',
    email: 'info@takahashi-setsubi.co.jp',
    notes: '給排水・空調設備工事全般対応可能。',
    registeredDate: '2017-09-10',
    updatedDate: '2025-09-20',
  },
  {
    id: '6',
    companyName: '伊藤製作所',
    companyNameKana: 'イトウセイサクショ',
    representative: '伊藤五郎',
    address: '神奈川県川崎市川崎区東田町6-6-6',
    phone: '044-6789-0123',
    email: 'ito@ito-seisakusho.com',
    notes: '機器制作に特化。カスタム制作対応可能。',
    registeredDate: '2020-11-05',
    updatedDate: '2025-08-30',
  },
  {
    id: '7',
    companyName: '渡辺メンテナンス',
    companyNameKana: 'ワタナベメンテナンス',
    representative: '渡辺六郎',
    address: '東京都品川区大崎7-7-7',
    phone: '03-7890-1234',
    email: 'watanabe@watanabe-maintenance.jp',
    notes: '保守点検業務専門。定期点検契約多数。',
    registeredDate: '2019-02-14',
    updatedDate: '2025-09-10',
  },
];

// 協力会社書類モックデータ
export const mockPartnerDocuments = [
  { id: 'd1', partnerId: '1', fileName: '会社概要_山本工業.pdf', filePath: '/documents/partner1/company_profile.pdf', fileSize: 1024000, uploadedDate: '2025-09-15' },
  { id: 'd2', partnerId: '1', fileName: '保険証券_2025.pdf', filePath: '/documents/partner1/insurance_2025.pdf', fileSize: 512000, uploadedDate: '2025-09-15' },
  { id: 'd3', partnerId: '2', fileName: '会社案内_田中電気.pdf', filePath: '/documents/partner2/company_guide.pdf', fileSize: 2048000, uploadedDate: '2025-08-20' },
  { id: 'd4', partnerId: '3', fileName: '営業許可証_佐藤建設.pdf', filePath: '/documents/partner3/business_license.pdf', fileSize: 768000, uploadedDate: '2025-09-01' },
  { id: 'd5', partnerId: '5', fileName: '施工実績書.xlsx', filePath: '/documents/partner5/track_record.xlsx', fileSize: 256000, uploadedDate: '2025-09-20' },
];